version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
   image: postgres:16
   environment:
     POSTGRES_DB: ${POSTGRES_DB}
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   volumes:
     - .:/docker-entrypoint-initdb.d
   ports:
     - "6543:5432"